# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
Armor.create([
  {
    name: "Shield (TL 0)",
    description: "Shields lower the armor class of users by 1 point against primitive weapons of tech level 3 or less.",
    ac: 0,
    ac_bonus: -1,
    damage_reduction: 0,
    cost: 10,
    tech_level: 0,
    encumbrance: 1,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Shield (TL 4)",
    description: "Shields lower the armor class of users by 1 point against primitive weapons of tech level 3 or less. This TL 4 model also functions against projectile weapons of TL 3 or less.",
    ac: 0,
    ac_bonus: -1,
    damage_reduction: 0,
    cost: 100,
    tech_level: 4,
    encumbrance: 1,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Leather Jack",
    description: "A leather coat. Weapons of TL 3 or higher weapons ignore this armor.",
    ac: 7,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 10,
    tech_level: 1,
    encumbrance: 0,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Metal Mail",
    description: "Low tech metal armor. Weapons of TL 3 or higher ignore this armor.",
    ac: 5,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 50,
    tech_level: 1,
    encumbrance: 2,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Metal Plate",
    description: "Low tech metal plate armor. Weapons of TL 3 or higher ignore this armor.",
    ac: 3,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 100,
    tech_level: 1,
    encumbrance: 2,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Woven Body Armor",
    description: "Composed of composites, plastics, and ceramic inserts. Bulky and cumbersome, but effective under most circumstances. Default TL 3 Armor.",
    ac: 5,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 400,
    tech_level: 3,
    encumbrance: 1,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Armored Undersuit",
    description: "Skin-tight metaplast bodysuit. All but invisible under normal clothing. A popular choice for adventurers wishing discreet protection.",
    ac: 7,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 600,
    tech_level: 4,
    encumbrance: 0,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Combat Field Uniform",
    description: "Standard TL 4 level combat dress for military units. A metaplast overlay on sintered microceramic plates. It absorbs impacts, thermal shocks, and shearing blows well. It is substantially lighter than woven body armor.",
    ac: 4,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 1000,
    tech_level: 4,
    encumbrance: 0,
    ammo_id: null,
    ammo_efficiency: 0
  },
  {
    name: "Assault Suit",
    description: "An Assault Suit requires Exosuit training or the wearer sufferes a -2 penalty to hit. Level 0 Exosuit is sufficient to remove this penalty. Assault suits have self-contained atmospheres and can be used as a vacuum suit for up to six hours before requiring atmosphere recharging. Assault suits grant immunity to injury from unarmed attacks or portable (non-gunnery) weapons of TL 3 or lower. Alien creatures have natural attacks that often overcome this immunity. An assault suit requires a Type A power cell for each 24 hours of operation.",
    ac: 2,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 6000,
    tech_level: 4,
    encumbrance: 2,
    ammo_id: Ammunition.findByName("Type A Power Cell").id,
    ammo_efficiency: 1
  },
  {
    name: "Powered Armor",
    description: "Powered Armor requires Exosuit training or the wearer sufferes a -4 penalty to hit. Level 1 Exosuit is sufficient to remove this penalty. Power Armor has self-contained atmospheres and can be used as a vacuum suit for up to six hours before requiring atmosphere recharging. Powered Armor allows the wearer to carry an additional two items readied, and an additional four items stowed without encumberance. Power Armor grants immunity to injury from unarmed attacks or portable (non-gunnery) weapons of TL 3 or lower. Alien creatures have natural attacks that often overcome this immunity. Powered Armor requires a Type A power cell for each 24 hours of operation.",
    ac: 1,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 10000,
    tech_level: 4,
    encumbrance: 2,
    ammo_id: Ammuition.findByName("Type A Power Cell").id,
    ammo_efficiency: 1
  },
  {
    name: "Field Emitter Panoply",
    description: "A FEP is an exoskeletal energy array which bubbles the wearer in close-fitting damper fields. These fields filter most radiation and all microorganisms. Integral atmosphere crackers allow the use of an FEP as a vacuum suit indefnitely. FEPs grant immunity to injury from unarmed attacks or portable (non-gunnery) weapons of TL 3 or lower. An FEP requires one Type A power cell for each 24 hours of operation.",
    ac: 0,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 30000,
    tech_level: 5,
    encumbrance: 1,
    ammo_id: Ammunition.findByName("Type A Power Cell").id,
    ammo_efficiency: 1
  },
  {
    name: "Deflector Array",
    description: "A subtler FEP. Deflector Array fields are invisible except when they are deflecting attacks. Deflector arrays can be worn beneath ordinary clothing. The array cannot be used as a vacuum suit or environmental protection, and grants no special protection against primitive weapondry. A deflector array requires one Type A power cell for each 24 hours of operation.",
    ac: 2,
    ac_bonus: 0,
    damage_reduction: 0,
    cost: 30000,
    tech_level: 5,
    encumbrance: 0,
    ammo_id: Ammunition.findByName("Type A Power Cell").id,
    ammo_efficiency: 1
  },
]);

Asset.create([
  {
    name: "Security Personnel",
    description: "Standard Civilian guards of policemen, usually equipped with nonlethal weapondry or personal sidearms.",
    max_hp: 3,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 2,
    upkeep: 0,
    tech_level: 0,
    asset_level: 1,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "1d3+1",
    couter_roll: "1d4",
    special: null,
  },
  {
    name: "Hitmen",
    description: "Crudely-equipped thug and assasins with minimal training that have been aimed at a rival faction's leadership.",
    max_hp: 1,
    asset_type: "Special Forces",
    attribute_type: "Force",
    cost: 2,
    upkeep: 0,
    tech_level: 0,
    asset_level: 1,
    attack_attribute: "Force",
    defense_attribute: "Cunning",
    attack_roll: "1d6",
    couter_roll: null,
    special: null,
  },
  {
    name: "Militia Unit",
    description: "Lightly-equipped irregular troops with rudimentary military training but no heavy support.",
    max_hp: 4,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 4,
    upkeep: 0,
    tech_level: 3,
    asset_level: 1,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "1d6",
    couter_roll: "1d4+1",
    special: "Permission Required",
  },
  {
    name: "Base of Influence",
    description: "A base of influence is specail, and represents a factions headquarters, industry, and/or other presence on a world. Bases of Influence can only be founded via the 'expand influence' action. Any damage done to a Base of Influence is also done to a faction's hit points. The cost of a Base of Influence is equal to it's maximum hit points, up to the total hitpoints of it's owning faction. A faction's Bases of Influence don't count against their maximum asets.",
    max_hp: 0,
    asset_type: "Special",
    attribute_type: "Special",
    cost: 0,
    upkeep: 0,
    tech_level: 0,
    asset_level: 1,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Heavy Drop Assets",
    description: "Allows for the transport of resources from one world to another. As an action, any one non-Starship asset (including this one) may be moved to any world within one hex for one FacCred.",
    max_hp: 6,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 4,
    upkeep: 0,
    tech_level: 4,
    asset_level: 2,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "A",
  },
  {
    name: "Elite Skirmishers",
    description: "Lightly-equipped troops trained for guerilla warefare and quick raids.",
    max_hp: 5,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 5,
    upkeep: 0,
    tech_level: 4,
    asset_level: 2,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "2d4",
    couter_roll: "1d4+1",
    special: "Permision Required",
  },
  {
    name: "Hardened Personnel",
    description: "Employees and support staff that have been trained in defensive fighting and equipped with supply caches and hardened fallback positions.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Force",
    cost: 4,
    upkeep: 0,
    tech_level: 3,
    asset_level: 2,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: "1d4+1",
    special: null,
  },
  {
    name: "Guerilla Populace",
    description: "Popular support among the locals and a cadre of men and women willing to fight as partisans.",
    max_hp: 6,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 4,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Force",
    defense_attribute: "Cunning",
    attack_roll: "1d4+1",
    couter_roll: null,
    special: null,
  },
  {
    name: "Zealots",
    description: "Members of the faction so utterly dedicated that they are willing to commit suicide attacks. Zealots take 1d4 damage every time tey launch a successful attack or perform a counter-attack.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Force",
    cost: 6,
    upkeep: 0,
    tech_level: 0,
    asset_level: 3,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "2d6",
    couter_roll: "2d6",
    special: "Special Rules",
  },
  {
    name: "Cunning Trap",
    description: "Involve all the myriad stratagems of war, from induced landslides to spreading local diseases.",
    max_hp: 2,
    asset_type: "Tactic",
    attribute_type: "Force",
    cost: 5,
    upkeep: 0,
    tech_level: 0,
    asset_level: 3,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: "1d6+3",
    special: null,
  },
  {
    name: "Counterintel Unit",
    description: "Specialize in code breaking, internal security, and monitoring duties. They can crack open enemy plots long before they have time to come to fruition.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Force",
    cost: 6,
    upkeep: 0,
    tech_level: 4,
    asset_level: 3,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "1d4+1",
    couter_roll: "1d6",
    special: null,
  },
  {
    name: "Beachhead Landers",
    description: "A collection of short-range, high-capacity spike driver ships capable of moving large numbers of troops. As an action, the asset may move any number of assets on the planet (including itself) to any world within on hex at a cost of one FacCred per asset moved.",
    max_hp: 10,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 10,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Action",
  },
  {
    name: "Extended Theater",
    description: "Allows for transporting assets long distances. As an action, any one non-Starship asset (including itself) can be moved between any two worlds within two hexes of the extended theater, at a cost of 1 FacCred.",
    max_hp: 10,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 10,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Specal Action",
  },
  {
    name: "Strike Fleet",
    description: "Composed of frigate or cruiser-class vessels equipped with space-to-ground weaponry and sophisticated defenses against light planetary weaponry. As an action, they can move to any world within one hex of their current location.",
    max_hp: 8,
    asset_type: "Starship",
    attribute_type: "Force",
    cost: 12,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "2d6",
    couter_roll: "1d8",
    special: "Special Action",
  },
  {
    name: "Postech Infantry",
    description: "The backbone of most planetary armies. These well-trained soldiers are usually equipped with mag weaponry and combat field uniforms, and have heavy support units attached.",
    max_hp: 12,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 8,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "1d8",
    couter_roll: "1d8",
    special: "Permission Required",
  },
  {
    name: "Blockade Fleet",
    description: "A ragtag lot of corsairs, pirates, privateers, and other deniable assets. When they successfully hit an enemy faction asset, they steal 1d4 FacCreds from the target faction as well. The theft can occur only once per turn per faction, even if multiple blockade fleets owned by that faction attack.",
    max_hp: 8,
    asset_type: "Starship",
    attribute_type: "Force",
    cost: 10,
    upkeep: 0,
    tech_level: 4,
    asset_level: 0,
    attack_attribute: "Force",
    defense_attribute: "Wealth",
    attack_roll: "1d6",
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Pretech Logistics",
    description: "Caches, smugglers, or internal research and salvage programs. As an action a pretech logistics asset allows the owner to buy one Force asset on that world that requires up to TL 5 to purchase. This asset costs 1.5 times the normal cost, rounded up. Only one asset can be purchased per turn.",
    max_hp: 6,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 14,
    upkeep: 0,
    tech_level: 0,
    asset_level: 5,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Action",
  },
  {
    name: "Psychic Assassins",
    description: "Combat trained Psychics equipped with advanced pretech stealth gear and psitech weaponry. Psychic assassins automatically start Stealthed when purchased.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Force",
    cost: 12,
    upkeep: 0,
    tech_level: 4,
    asset_level: 5,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "2d6+2",
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Pretech Infantry",
    description: "The cream of the stellar ground forces, elite troops kitted out in the best pretech weaponry and armor available with sophisticated heavy support weaponry integral to the unit.",
    max_hp: 20,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 16,
    upkeep: 0,
    tech_level: 5,
    asset_level: 6,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "2d8",
    couter_roll: "2d8+2",
    special: "Permission Required",
  },
  {
    name: "Planetary Defenses",
    description: "Massive Mag Cannons and Seeker Missile Arrays designed to defend against starship bombardments. Planetary Defenses can only defend against attacs by Starship-type assets.",
    max_hp: 18,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 20,
    upkeep: 0,
    tech_level: 4,
    asset_level: 6,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: "2d6+6",
    special: "Special Rules",
  },
  {
    name: "Gravtank Formation",
    description: "Advanced pretech gravtank units that are capable of covering almost any terrain and cracking the toughest defensive positions.",
    max_hp: 14,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 25,
    upkeep: 0,
    tech_level: 5,
    asset_level: 6,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "2d10+4",
    couter_roll: "1d10",
    special: "Permission Required",
  },
  {
    name: "Deep Strike Landers",
    description: "Advanced Pretech transport ships capable of moving an asset long distances. As an action, any one non-Starship asset (including itself) can be moved between any two wolrds within three hexes of the deep strike landers, at a cost of 2 FacCreds.",
    max_hp: 10,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 25,
    upkeep: 0,
    tech_level: 5,
    asset_level: 7,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Action",
  },
  {
    name: "Integral Protocols",
    description: "A complex web of braked-AI supported sensors and redundant security checks used to defeat attempts to infiltrate an area. They can defend only against attacks versus Cunning, but they add an additional die to the defender's roll.",
    max_hp: 10,
    asset_type: "Facility",
    attribute_type: "Force",
    cost: 20,
    upkeep: 0,
    tech_level: 5,
    asset_level: 7,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: "2d8+2",
    special: "Special Rules",
  },
  {
    name: "Space Marines",
    description: "Heavily-Armored specailist troops trained for ship boarding actions and opposed landings. As an action, they can move to any world within one hex of their current location, whether or not the planetary government permits it.",
    max_hp: 16,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 30,
    upkeep: 0,
    tech_level: 5,
    asset_level: 7,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "2d8+2",
    couter_roll: "2d8",
    special: "Special Action",
  },
  {
    name: "Capital Fleet",
    description: "The pride of an empire, a collection of massive pretech warships without peer in most sectors. Capital fleets are expensive to keep flying, and cost an additional 2 FacCreds of maintenance each turn. As an action, they may move to any world within three hexes of their current location. Planetary government permission is required to raise a captial fleet, but not to move one into a system.",
    max_hp: 30,
    asset_type: "Spaceship",
    attribute_type: "Force",
    cost: 40,
    upkeep: 2,
    tech_level: 5,
    asset_level: 8,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "3d10+4",
    couter_roll: "3d8",
    special: "Special Action, Special Rules",
  },
  {
    name: "Smugglers",
    description: "Skilled in extracting personnel. For one FacCred the the smugglers can transport itself or any one Special Forces unit to a planet up to two hexes away.",
    max_hp: 4,
    asset_type: "Starship",
    attribute_type: "Cunning",
    cost: 2,
    upkeep: 0,
    tech_level: 4,
    asset_level: 1,
    attack_attribute: "Cunning",
    defense_attribute: "Wealth",
    attack_roll: "1d4",
    couter_roll: null,
    special: "Special Action",
  },
  {
    name: "Informers",
    description: "Informers lace a planet's underworld, watchful for intruders. They can choose to Attack any faction, and need not specify a particular asset to target. On a successful Cunning vs Cunning attack, all Sealthed assets on the planet belonging to that faction are revealed. Informers can target a faction even if none of their assets are visible on a world; at worst, they siply learn that there are no stealthed assets there.",
    max_hp: 3,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 2,
    upkeep: 0,
    tech_level: 0,
    asset_level: 1,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: null,
    couter_roll: null,
    special: "Special Action, Special Rules",
  },
  {
    name: "False Front",
    description: "Allows a faction to preserve more valuable resources. If another asset on the planet suffers enough damage to destroy it, the feaction can sacrifice the false front instead to nullify the killing blow.",
    max_hp: 2,
    asset_type: "Logistics Facility",
    attribute_type: "Cunning",
    cost: 1,
    upkeep: 0,
    tech_level: 0,
    asset_level: 0,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Lobbyists",
    description: "Used to block the governmental permission that is sometime required to buy and asset or transport it into a system. When a rival faction gains permission to do so, the Lobbyists can make an immediate Cunning vs Cunning test against teh faction; if the test is successful the permission is withdrawn and cannot be attmpted again until the next turn.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 4,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Saboteurs",
    description: "Trained in launching strikes against crucial enemy operations. An asset attacked by saboteurs cannot use any Action ability until the start of the attacking faction's next turn. This lock applies whether or note the saboteurs' attack was successful.",
    max_hp: 6,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 3,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "2d4",
    couter_roll: null,
    special: "Specal Rules",
  },
  {
    name: "Blackmail",
    description: "Used to selectively degrade the effectiveness of an enemy asset. Any attempt to attack or defend against Blackmail loses any bonus dice earned by tags.",
    max_hp: 4,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 4,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "1d4+1",
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Seductress",
    description: "Seductresses and Seducers subvert the leadership of enemy assets, revealing hidden plans. As an action, a Seductress does no damage, but an asset that has been successfully attacked immediately reveals any other Stealthed assets on the planet. Only Special Foces units can attack a Seductress.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 5,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Cyberninjas",
    description: "Outfitted with the latest in personal stealth cyberware all desiged to avoid all but the most careful scans and inspections.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 6,
    upkeep: 0,
    tech_level: 4,
    asset_level: 3,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "2d6",
    couter_roll: null,
    special: null,
  },
  {
    name: "Stealth",
    description: "A special quality that can be purchased for another Special Forces asset on the world. An asset that has been Stealthed cannot be detected or attacked by other factions. If the unit normally requires the ermission of a planetary government to be moved onto a plaent, it ignores that requirement. An asset loses its Stealth when it attacks or defends.",
    max_hp: 0,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 3,
    upkeep: 0,
    tech_level: 0,
    asset_level: 3,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Covert Shipping",
    description: "A clandestine shipping network. Allows for the quiet transportation of a unit from one world to another. Any one Special Forces unit can be moved between any worlds within three hexes of the Covert Shipping at the cost of one FacCred.",
    max_hp: 4,
    asset_type: "Logistic Facility",
    attribute_type: "Cunning",
    cost: 8,
    upkeep: 0,
    tech_level: 4,
    asset_level: 3,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules, Special Action",
  },
  {
    name: "Party Machine",
    description: "Political blocks that control particular cities or regions; blocks are are firmly in control of the faction. Each turn, a Party Machine provides 1 FacCred to its owning faction.",
    max_hp: 10,
    asset_type: "Logistics Facility",
    attribute_type: "Cunning",
    cost: 10,
    upkeep: 0,
    tech_level: 0,
    asset_level: 4,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "2d6",
    couter_roll: "1d6",
    special: "Special Rules",
  },
  {
    name: "Vanguard Cadres",
    description: "Followers of the moevement inspired sufficiently to take up arms and fight on behalf of their leadership.",
    max_hp: 12,
    asset_type: "Military Unit",
    attribute_type: "Cunning",
    cost: 8,
    upkeep: 0,
    tech_level: 3,
    asset_level: 4,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "1d6",
    couter_roll: "1d6",
    special: null,
  },
  {
    name: "Tripwire Cells",
    description: "Passive observers intended to alert the faction on the arrival of stealthed units. Whenever a stealthed asset lands or is purchased on a planet with tripwre cells, the Cells make an immediate Cunning vs Cunning attack against the owning faction. If successful, the target loses its stealth.",
    max_hp: 8,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 12,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: "1d4",
    special: "Special Action, Special Rules",
  },
  {
    name: "Seditionists",
    description: "Units who baffle and confuse their targets, sapping their will to obey. For a cost of 1d4 FacCreds, the Seditionists can attach themselves to an enemy asset. Until they attach to a different asset or no longer share the same planet, the affected asset cannot perform an attack action.",
    max_hp: 8,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 12,
    upkeep: 0,
    tech_level: 0,
    asset_level: 4,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Action",
  },
  {
    name: "Organization Moles",
    description: "Subvert and confuse enemy assets, striking to damage their cohesion.",
    max_hp: 8,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 10,
    upkeep: 0,
    tech_level: 0,
    asset_level: 5,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "2d6",
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Cracked Comms",
    description: "A cryptographic weakness discovered in enemy communcations. Friendly Fire can be induced with the right interferenece. If Cracked Comms succeeds in defending against an attack, it can immediately cause the asset to attack itself for normal damage and counterattack consequences.",
    max_hp: 6,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 14,
    upkeep: 0,
    tech_level: 0,
    asset_level: 5,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Boltholes",
    description: "A hideout equipped with a number of postech innovations to make cleaning them out a costly and dangerous pursuit. If a faction Special Forces or Military Unit asset on the same planet as the Boltholes suffers damage sufficient to destroy it, it is instead set at 0 HP and rendered untouchable and unusable until it is repaired to full strength. If the Boltholes are destroyed before this happens, the asset is destroyed with them.",
    max_hp: 6,
    asset_type: "Logistics Facility",
    attribute_type: "Cunning",
    cost: 12,
    upkeep: 0,
    tech_level: 4,
    asset_level: 5,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: "2d6",
    special: "Special Rules",
  },
  {
    name: "Transport Lockdown",
    description: "Selective pressure applied to local routing and shipping companies. On a successful Cunning vs Cunning attack against a rival faction, the target faction cannot transport assets onto that planet without spending an additional 1d4 FacCreds and waiting one turn.",
    max_hp: 10,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 20,
    upkeep: 0,
    tech_level: 4,
    asset_level: 6,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: null,
    couter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Covert Transit Net",
    description: "An area of space with a network of smugglers and grey-market freighter captains. As an action, any Special Forces assets can be moved between any worlds within three hees of the Covert Transit Net.",
    max_hp: 15,
    asset_type: "Logistics Facility",
    attribute_type: "Cunning",
    cost: 18,
    upkeep: 0,
    tech_level: 4,
    asset_level: 6,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    couter_roll: null,
    special: "Sepcial Action",
  },
  {
    name: "Demagogue",
    description: "Popular leaders of a particular faith of ideology that can be realied upon to point their followers in the direction of maximum utility for the faction.",
    max_hp: 1-,
    asset_type: "Special Forces",
    attribute_type: "Cunning",
    cost: 20,
    upkeep: 0,
    tech_level: 0,
    asset_level: 6,
    attack_attribute: "Cunning",
    defense_attribute: "Cuning",
    attack_roll: "2d8",
    counter_roll: "1d8",
    special: null,
  },
  {
    name: "Popular Movement",
    description: "A planet-wide surge of enthusiasm for a cause controlled by the faction. The support pervades all levels of government, and the government always grants any asset purchase or movement requests made by the faction.",
    max_hp: 16,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 25,
    upkeep: 0,
    tech_level: 4,
    asset_level: 7,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: "2d6",
    counter_roll: "1d6",
    special: "Special Rules",
  },
  {
    name: "Book of Secrets",
    description: "Exhaustively catalogued psychometric records on important and influential local figures. It allows for uncanny accuracy in predicting their actions. Once per turn a Book of Secrets allows the faction to reroll one die for an action taken on that world or force an enemy faction to reroll one die. This reroll can only be forced once per turn, even if the faction owns multiple Book of Secrets assets.",
    max_hp: 10,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 20,
    upkeep: 0,
    tech_level: 4,
    asset_level: 7,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "2d8",
    special: "Special Rules",
  },
  {
    name: "Treachery",
    description: "Attacks an enemy asset. On a successful attack, the Treachery asset is lost, 5 FacCreds are gained, and the targeted asset joins the attacking faction, even if the faction does not have the necessary requirements to purchase it.",
    max_hp: 5,
    asset_type: "Tactic",
    attribute_type: "Cunning",
    cost: 10,
    upkeep: 0,
    tech_level: 0,
    asset_level: 7,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Panopticon Matrix",
    description: "A weave of braked-AI intelligence analysts and observation hardware capable of detecting the slightest evidence of intruders on a world. Every rival Stealthed asset on the planet must succeed in a Cunning vs CUnning test at the beginning of every turn or lose their Stealth. The owner also gains an additional die on all Cunning attacks and defenses on that planet.",
    max_hp: 20,
    asset_type: "Logistics Facility",
    attribute_type: "Cunning",
    cost: 30,
    upkeep: 0,
    tech_level: 5,
    asset_level: 8,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "1d6",
    special: "Special Rules",
  },
  {
    name: "Franchise",
    description: "A deniable connection with a local licensee for the faction's goods and services. When a Franchise successfully attacks an enemy asset, the enemy faction loses one FacCred (if they have any). which is gained by the Franchise's owner. The loss can only happen once per turn, no matter how many Franchises attack.",
    max_hp: 3,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 2,
    upkeep: 0,
    tech_level: 2,
    asset_level: 1,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "1d4",
    counter_roll: "1d4-1",
    special: "Special Rules",
  },
  {
    name: "Harvesters",
    description: "Machines and personelle who gather the natural resources of a world (whether ore, biologicals or other unprocessed natural goods). As an action, the Harvesters' owning faction may roll 1d6. On a 4 or more one FacCred is gained.",
    max_hp: 4,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 2,
    upkeep: 0,
    tech_level: 0,
    asset_level: 1,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "1d4",
    special: "Special Rules",
  },
  {
    name: "Local Investments",
    description: "Gives the faction substanial influence over commerce on a world. Any other faction that tries to buy an asset on the planet must pay one extra FacCred. This money is not given to the investments owner, but is lost. This penalty is only applied once, no matter how many Local Investments are present on a world.",
    max_hp: 2,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 1,
    upkeep: 0,
    tech_level: 2,
    asset_level: 1,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "1d4-1",
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Freighter Contract",
    description: "Special links with heavy shipping spacers. As an action, the faction may move any one non-Force asset (including this one) to any world within two hexes at a cost of one FacCred.",
    max_hp: 4,
    asset_type: "Starship",
    attribute_type: "Wealth",
    cost: 5,
    upkeep: 0,
    tech_level: 4,
    asset_level: 2,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "1d4",
    counter_roll: null,
    special: "Special Action",
  },
  {
    name: "Lawyers",
    description: "Lawyers in the universal sense, from sophists in immaculate suits to charismatic tribal skalds. Lawyers have the ability to tie an enemy up in the knots of their own rules, damaging assets with confusion and red tape. Lawyers cannot attack or counterattack Force assets.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Wealth",
    cost: 6,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Cunning",
    defense_attribute: "Wealth",
    attack_roll: "2d4",
    counter_roll: "1d6",
    special: "Special Rules",
  },
  {
    name: "Union Toughs",
    description: "Don't much like scabs and management. They're willing to take the faction's word on which people are which. They're lightly armed and poorly trained, but they can often infiltrate to perform sabotage when neccessary.",
    max_hp: 6,
    asset_type: "Military Unit",
    attribute_type: "Wealth",
    cost: 4,
    upkeep: 0,
    tech_level: 0,
    asset_level: 2,
    attack_attribute: "Wealth",
    defense_attribute: "Force",
    attack_roll: "1d4+1",
    counter_roll: "1d4",
    special: null,
  },
  {
    name: "Surveyors",
    description: "Explore optential resource and investment options on worlds. The presence of a Surveyor crew allows on additional die to be rolled on Expand Influence actions. As an action, a surveyor crew can be moved to any world within two hexes.",
    max_hp: 4,
    asset_type: "Special Forces",
    attribute_type: "Wealth",
    cost: 4,
    upkeep: 0,
    tech_level: 4,
    asset_level: 2,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "1d4",
    special: "Special Rules, Special Action",
  },
  {
    name: "Postech Industry",
    description: "Produces a wide range of postech products out of local resources. As an action, the owning faction can roll 1d6 for a Postech Industry asset. On a 1, one FacCred is lost, on a 2 no profit is gained, on a 3-5 on FacCred is earned, and a 6 generates two FacCreds. If money is lost and no resources are available to pay for it, the Postech Industry is destroyed.",
    max_hp: 4,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 8,
    upkeep: 0,
    tech_level: 4,
    asset_level: 3,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "1d4",
    special: "Special Action",
  },
  {
    name: "Laboratory",
    description: "Allows a world to make hesitant progress in tech. The presence of a Laboratory allows assets to be purchased on that world as if it had tech level 4, at +2 cost.",
    max_hp: 4,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 6,
    upkeep: 0,
    tech_level: 0,
    asset_level: 0,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Mercenaries",
    description: "Groups of well-equipped, highly-trained soldiers willing to serve the highest bidder. Mercenaries have a maintenance cost of one FacCred per turn. As an action, Mercenaries can move to any world within one hex of their current location. To purchase or move a Mercenary asset to a planet requires government permission.",
    max_hp: 6,
    asset_type: "Military Unit",
    attribute_type: "Wealth",
    cost: 8,
    upkeep: 1,
    tech_level: 4,
    asset_level: 3,
    attack_attribute: "Wealth",
    defense_attribute: "Force",
    attack_roll: "2d4+2",
    counter_roll: "1d6",
    special: "Special Rules, Special Action, Permission Required",
  },
  {
    name: "Shipping Combine",
    description: "Allow almost effortless relocation of all assets. For one FacCred, any number of non-starship Cunning or Wealth assets may be moved between any two worlds within three hexes of the Transit Web. This may be done freely on the owner's turn so long as the transit fee can be paid and does not require the use of an action.",
    max_hp: 10,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 10,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "1d6",
    special: "Special Action",
  },
  {
    name: "Monopoly",
    description: "An open or tacit stranglehold on certain businesses or resources on a world. As an action, owners of a monopoly may force one other faction with unstealthed assets on that world to pay them one FacCred. If the target faction doesn't have the resources to pay, they lose one asset of their choice on the world.",
    max_hp: 12,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 8,
    upkeep: 0,
    tech_level: 3,
    asset_level: 4,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "1d6",
    counter_roll: "1d6",
    special: "Special Rules",
  },
  {
    name: "Medical Center",
    description: "Allow for the salvage and repair of damaged assets. Once, between turns, if a Special Forces or Military Unit asset on the world is destroyed, the faction may immediately pay half it's purchase cost to restore it with one hit point. Any Repair Asset actions taken on that world cost one less FacCred for Special Forces and Military Units.",
    max_hp: 8,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 12,
    upkeep: 0,
    tech_level: 4,
    asset_level: 4,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Bank",
    description: "Protects wealth. Once per turn the faction can ignore one cost or FacCred loss imposed by another fation, regardless of where it is levied. Factions may stack multiple banks to allow multiple losses to be ignored.",
    max_hp: 8,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 12,
    upkeep: 0,
    tech_level: 2,
    asset_level: 3,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Marketers",
    description: "Deployed to confuse enemy factions into untimely investments and paralyze them with incompatable hardware and software. As an action, the marketers may test Cunnig vs Wealth targeting a rival factions asset. If successful the target faction must immediately pay half the asset's purchase cost, rounded down, or have it become disabled until they choose to pay.",
    max_hp: 8,
    asset_type: "Tactic",
    attribute_type: "Wealth",
    cost: 10,
    upkeep: 0,
    tech_level: 0,
    asset_level: 5,
    attack_attribute: "Cunning",
    defense_attribute: "Wealth",
    attack_roll: "1d6",
    counter_roll: null,
    special: "Special Action",
  },
  {
    name: "Pretech Researchers",
    description: "A highly versatile team of research and design specailists capable of brining the most backward planet up to pretech self-sufficiently. Any world with PRetech Researchers on it is treated as TL 5 for the purpose of buying Cunning and Wealth assets. Pretech researchers have a maintenance cost of 1 FacCred per turn.",
    max_hp: 6,
    asset_type: "Special Forces",
    attribute_type: "Wealth",
    cost: 14,
    upkeep: 1,
    tech_level: 4,
    asset_level: 5,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Blockade Runners",
    description: "Starship captains that excel at transporting goods through unfriendly lines. As an action, a blockade runner can transfer itself or any one Military Unit or Special Forces to a world within three hexes for a cost of two FacCreds. Blockade Runners can even move units that would otherwise require planetary government permission to be imported into a world.",
    max_hp: 6,
    asset_type: "Starship",
    attribute_type: "Wealth",
    cost: 12,
    upkeep: 0,
    tech_level: 4,
    asset_level: 5,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: "2d4",
    special: "Special Action",
  },
  {
    name: "Venture Capital",
    description: "Grows assets out of seemingly nowhere, harvesting the best of entrepreneurship for the faction's benefit. As an action venture capital can be tapped. 1d8 is rolled. One a 1 the asset is destroyed, on 2-4 one FacCred is gained. 5-7 produces two FacCreds and an 8 gains 3 FacCreds.",
    max_hp: 10,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 15,
    upkeep: 0,
    tech_level: 4,
    asset_level: 6,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "2d6",
    counter_roll: "1d6",
    special: "Special Action",
  },
  {
    name: "Research and Development",
    description: "The smooth extension of wealth-creation and industrial principles to the farthest reaches of the faction's operations. A faction with an R&D department may treat all planets as if they were TL 4 for the purposes of purchasing wealth assets.",
    max_hp: 15,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 18,
    upkeep: 0,
    tech_level: 4,
    asset_level: 6,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Commodities Broker",
    description: "Substaintially lessens the cost of large-scale investments by timing materials purchases to coincie with gluts in the market. As an action the owner of a commodities broker can roll 1d8. The result of that roll reduces the cost of their next asset purchase, down to a minimum of half, rounded down.",
    max_hp: 10,
    asset_type: "Special Forces",
    attribute_type: "Wealth",
    cost: 20,
    upkeep: 0,
    tech_level: 0,
    asset_level: 6,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "2d8",
    counter_roll: "1d8",
    special: "Special Action",
  },
  {
    name: "Pretech Manufactory",
    description: "Rare, precious examples of functioning pretech industrial facilities, retrofitted to work without the benefit of specialized psychic disciplines. as an action, the owning faction can roll 1d8 for a Pretech Manufactory, and gain half that many FacCreds, rounded up.",
    max_hp: 16,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 25,
    upkeep: 0,
    tech_level: 5,
    asset_level: 7,
    attack_attribute: null,
    defense_attribute: null,
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Hostile Takeover",
    description: "Allows a faction to seize control of damaged and pooly-controlled assets. If a Hostile Takeove does enough damage to destroy an asset, the target is instead reduced to 1 hit point and acquired by the Hostile Takeover's owning faction.",
    max_hp: 16,
    asset_type: "Tactic",
    attribute_type: "Wealth",
    cost: 20,
    upkeep: 0,
    tech_level: 4,
    asset_level: 7,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "2d10",
    counter_roll: "2d8",
    special: "Special Rules",
  },
  {
    name: "Transit Web",
    description: "Allows almost effortless relocation of all assets. For one FacCred any number of non-starship Cunning or Wealth assets may be moved between any two worlds within three Hexes of the Transit Web. This may be done freely on the owner's turn so long as the transit fee can be paid and does not require the use of an action.",
    max_hp: 5,
    asset_type: "Facility",
    attribute_type: "Wealth",
    cost: 15,
    upkeep: 0,
    tech_level: 5,
    asset_level: 7,
    attack_attribute: "Cunning",
    defense_attribute: "Cunning",
    attack_roll: null,
    counter_roll: null,
    special: "Special Rules",
  },
  {
    name: "Scavenger Fleet",
    description: "These rag-tag armadas bring enormous technical and mercantile resources to their patrons, along with a facility sporting heavy guns. As an action, a Scavenger Fleet can be moved to any world within three hexes. Scavenger fleets cost 2 FacCreds per turn in maintenance.",
    max_hp: 20,
    asset_type: "Starship",
    attribute_type: "Wealth",
    cost: 30,
    upkeep: 2,
    tech_level: 5,
    asset_level: 8,
    attack_attribute: "Wealth",
    defense_attribute: "Wealth",
    attack_roll: "2d10+4",
    counter_roll: "2d10",
    special: null,
  },
  {
    name: "Gengineered Slaves",
    description: "Once per turn, the Eugenics Cult can roll an extra d10 on an attack or defense by a Gengineered Slaves asset.",
    max_hp: 6,
    asset_type: "Military Unit",
    attribute_type: "Force",
    cost: 2,
    upkeep: 0,
    tech_evel: 4,
    asset_level: 1,
    attack_attribute: "Force",
    defense_attribute: "Force",
    attack_roll: "1d6",
    counter_roll: "1d4",
    special: "Eugenics Cult only",
]);

Tag.create([
  {
    name: "Colonists",
    description: "This faction has all the benefi ts of the Planetary Government tag for its homeworld, as no other government exists on a fresh colony. Th e faction’s homeworld is also treated as if it had at least tech level 4. Colonies with fewer than 100,000 citizens lack the necessary industrial infrastructure to build Spaceshiptype assets.",
  },
  {
    name: "Deep Rooted",
    description: "This faction can roll one additional d10 when defending against attacks on assets on their homeworld. If the faction ever changes homeworlds, this tag is lost."
  },
  {
    name: "Eugenics Cult",
    description: "The forbidden maltech secrets of advanced human genetic manipulation are known to this faction, and they use them with gusto. Slave-engineered humanoids and 'deathless' leadership are just two of the more common alterations these unstable, dangerous scientists undertake. Can purchase Gengineered Slaves.",
  },
  {
    name: "Exchange Consulate",
    description: "When the faction successfully completes a 'Peaceable Kingdom' goal, they may roll 1d6. On a 4+ they gain a bonus experience point. Once per turn the faction may roll an extra d10 when defending against a Wealth attack.",
  },
  {
    name: "Fanatical",
    description: "The faction rerolls any dice that come up 1. However they always lose ties during attacks.",
  },
  {
    name: "Imperialists",
    descrption: "This faction rolls an extra d10 for attacks made when taking a Seize Planet action.",
  },
  {
    name: "Machiavellian",
    description: "Once per turn, this faction can roll an additional d10 when making a Cunning attack.",
  },
  {
    name: "Mercinary Group",
    description: "All faction assets gain a special ability: As an action, this asset may move itself to any world within one hex.",
  },
  {
    name: "Perimeter Agency",
    description: "Once per turn, the faction may roll an additional d10 when making an attack that against a TL5 asset. The faction may roll an extra die when making a test to detect stealthed assets.",
  },
  {
    name: "Pirates",
    description: "Any movement of an asset onto a world that has a Base of Influence for this faction costs one extra FacCred, paid to this faction.",
  },
  {
    name: "Plutocratic",
    description: "Once per turn, this faction can roll an additional d10 when making a Wealth attack.",
  },
  {
    name: "Preceptor Archive",
    description: "Purchasing an asset that requires TL 4 or more costs one fewer FacCred than normal. The Preceptor Archive may also take the special action 'Teach Planetary Population', costing 2 FacCreds and allowing them to roll 1d12 for one world. On a 12, the world's tech level permanently becomes 4 for the purposes and purchases of this faction."
  },
  {
    name: "Psychic Academy",
    description: "This faction can provide psionic mentor training to qualified psychics. Once per turn, this faction can also force a rival faction to reroll any one d10, whether or not this faction s involved in the roll.",
  },
  {
    name: "Savage",
    description: "Once per turn ths faction can roll an extra die when defending with an asset that requires TL 0.",
  },
  {
    name: "Scavengers",
    description: "Whenever the faction destroys an asset or has one of their assets destroyed they gain one FacCred.",
  },
  {
    name: "Secretive",
    description: "All assets purchased by ths faction automatically become stealthed at purchase time.",
  },
  {
    name: "Technical Expertise",
    description: "This faction treats all planets at which they have a base of Influence as if they were at least TL4. They can build Starship-type assets on any world with at least 10k occupants",
  },
  {
    name: "Theocratic",
    description: "Once per turn, this faction can roll an extra d10 when defending against a Cunning attack.",
  },
  {
    name: "Warlike",
    description: "Once per turn, this faction can roll an additional d10 when making a Force attack.",
  },
  
   
 
]);
